version: 2
updates:
  - package-ecosystem: maven
    directories: 
      - "/**/*"
    schedule:
      interval: daily
    groups:
      maven-dependencies:
        patterns: 
        - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily

