steps:
  mavenBuild:
    verbose: false
    verify: true
    flatten: true
    # https://www.project-piper.io/steps/mavenBuild/#dockerimage
    # If empty, Docker is not used and the command is executed directly on the Jenkins system.
    dockerImage: ''

  detectExecuteScan:
    projectName: 'com.sap.cds.feature.event-hub'
    groups:
      - 'CDSJAVA-OPEN-SOURCE'
    serverUrl: 'https://sap.blackducksoftware.com/'
    mavenExcludedScopes: [ "provided", "test" ]
    failOn: [ 'BLOCKER', 'CRITICAL', 'MAJOR' ]
    versioningModel: "major-minor"
    detectTools: [ 'DETECTOR', 'BINARY_SCAN' ]
    installArtifacts: true
    repository: '/cap-java/cds-feature-event-hub'
    verbose: true
    scanProperties:
      - --detect.included.detector.types=MAVEN
      - --detect.excluded.directories='**/node_modules,**/*test*,**/localrepo,**/target/site,**/*-site.jar'
      - --detect.maven.build.command='-pl com.sap.cds:cds-feature-event-hub'
    # https://www.project-piper.io/steps/detectExecuteScan/#dockerimage
    # If empty, Docker is not used and the command is executed directly on the Jenkins system.
    dockerImage: ''

  sonarExecuteScan:
    serverUrl: https://sonar.tools.sap
    projectKey: cds-feature-event-hub
    # https://www.project-piper.io/steps/sonarExecuteScan/#dockerimage
    # If empty, Docker is not used and the command is executed directly on the Jenkins system.
    dockerImage: ''
    options:
      - sonar.qualitygate.wait=true
      - sonar.java.source=17
      - sonar.exclusions=**/node_modules/**,**/target/**
      - sonar.coverage.jacoco.xmlReportPaths=cds-feature-event-hub/target/site/jacoco/jacoco.xml
